[tool.mypy]
python_version = "3.9"
files = [
    "app",
    "scripts",
    "tests",
]
ignore_missing_imports = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_context = true
pretty = true

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
    "I",  # isort
    "B",  # flake8-bugbear
]
ignore = [
    "B008",  # function-call-argument-default
    "E402",  # module import not at top level (legacy scripts adjusting sys.path)
    "E501",  # line length, to be handled via formatter later
    "E722",  # bare except in historical scripts
    "F601",  # duplicate dict keys in legacy mapping tables
]

[tool.ruff.lint.isort]
known-first-party = ["app", "scripts", "tests"]
force-single-line = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
