"""共用標籤定義，避免重複維護。"""

from __future__ import annotations

from typing import FrozenSet

# 標準標籤列表（63 個）
VALID_TAGS: FrozenSet[str] = frozenset(
    {
        # 語法結構類 (Grammar Structures)
        "subjunctive",
        "conditional",
        "cleft",
        "inversion",
        "emphasis",
        "comparative",
        "superlative",
        "passive",
        "modal",
        "infinitive",
        "gerund",
        "participle",
        "relative-clause",
        "noun-clause",
        "adverb-clause",
        "as-clause",
        "complex-sentence",
        "grammar",
        # 特定語法結構類 (Specific Structures)
        "as-adjective-as",
        "as-soon-as",
        "as-long-as",
        "as-far-as",
        "the-more-the-more",
        "would-rather",
        "had-better",
        "used-to",
        "be-used-to",
        "too-to",
        "so-that",
        "such-that",
        "not-only-but-also",
        "either-or",
        "neither-nor",
        # 語法功能類 (Functions)
        "advice",
        "warning",
        "request",
        "permission",
        "prohibition",
        "suggestion",
        "offer",
        "invitation",
        "complaint",
        "apology",
        "opinion",
        "preference",
        "regret",
        "possibility",
        "necessity",
        "ability",
        "purpose",
        "result",
        "cause",
        # 語意主題類 (Semantic Themes)
        "family",
        "education",
        "career",
        "health",
        "money",
        "relationship",
        "travel",
        "food",
        "sports",
        "entertainment",
        "technology",
        "environment",
        "culture",
        "business",
        "academic",
        "personal",
        "social",
        "daily-life",
        # 時態語態類 (Tenses)
        "present-simple",
        "present-continuous",
        "present-perfect",
        "past-simple",
        "past-continuous",
        "past-perfect",
        "future-simple",
        "future-perfect",
    }
)

# 禁用標籤（供驗證腳本使用）
FORBIDDEN_TAGS: FrozenSet[str] = frozenset(
    {
        # 過於具體的詞彙
        "barbecue",
        "beer",
        "coffee",
        "marathon",
        "smartphone",
        "facebook",
        "instagram",
        "starbucks",
        "mcdonalds",
        "covid",
        "trump",
        "biden",
        "brexit",
        # 重複或冗餘的標籤
        "verb-of",
        "verb-from",
        "verb-noun-conversion",
        "hit-body-parts",
        "punch",
        "pat",
        "slap",
        "sensory-verbs",
        "causative-verbs",
        "location-verbs",
        # 過於細節的語法標籤
        "that-substitution",
        "those-substitution",
        "front-position",
        "back-position",
        "postposed",
        "one-other",
        "some-others",
        "former-latter",
        # 情境過度細化的標籤
        "breakfast",
        "dinner",
        "lunch",
        "cooking",
        "driving",
        "swimming",
        "cycling",
        "shopping",
        "birthday",
        "wedding",
        "vacation",
        "party",
    }
)

__all__ = ["VALID_TAGS", "FORBIDDEN_TAGS"]
